= Release notes

This page contains information about the changes between the different versions
of the CloudFiles library.

== Release 0.6 (2023-10-23)

* Replaced the dependencies to https://akka.io/[Akka] by https://pekko.apache.org/[Apache Pekko] because of the license change made by Akka.

== Release 0.5 (2022-03-13)

* Reduced logging for encrypted file systems containing elements with
  non-encrypted names. The exception stacktrace is no longer logged with level
  _WARN_, but with _DEBUG_ only.
* `DavFileSystem` can now be configured to explicitly request custom attributes
  from the server. For _PROPFIND_ requests without a body, it is obviously not
  guaranteed that the server includes all custom properties in the response.
  Therefore, in the configuration of `DavFileSystem`, it is now possible to
  specify the properties that should be loaded (together with the default
  properties evaluated by the file system). Per default, now only the standard
  DAV properties are loaded; so, applications making use of custom properties
  need to be updated to set the corresponding configuration property.

== Release 0.4 (2021-12-31)

* Improved `CryptNamesFileSystem` with regard to the handling of unencrypted
  file names. If a file system contained elements with unencrypted (or not
  properly Base64-encoded) names, these elements caused exceptions with cryptic
  messages or sometimes even crashes of certain components. The handling of
  such unexpected names has been improved in general: Exception messages now
  contain the problematic names. In the configuration of
  `CryptNamesFileSystem`, it is now possible to set a flag to ignore such
  names; they are then filtered out when listing the content of folders. To
  make the file system configurable in this regard, a new configuration class,
  `CryptNamesConfig` has been introduced; an instance of this new class is now
  expected by `CryptNamesFileSystem` rather than the generic `CryptConfig`
  class.
* Fixed a bug in OAuthExtension with the propagation of the
  `DiscardEntityMode` when forwarding requests. This parameter was not taken
  into account (causing the default mode to be used instead) when requests were
  passed through the chain of extensions.

== Release 0.3 (2021-09-24)

* Fixed the encoding handling when resolving paths in LocalFileSystem. The
  `resolvePath()` function now correctly decodes the passed in strings before
  they are converted to `Path` objects.
* `ElementPatchSpec` no longer supports patching the description field. While
  concrete `FileSystem` implementations may need to modify certain attributes,
  it is very unlikely that this would be required for the description.
* The type of the `description` property of files and folders has been changed
  from `String` to `Option[String]`. This better reflects the usage in
  practice, and is also more in-line with many concrete `FileSystem`
  implementations, for which this attribute is optional or even not supported.
* Changed the `RequestActorFactory` function type in `MultiHostExtension`. The
  new type no longer returns an `ActorRef`, but a `Future` with a function that
  actually creates the new request actor. This makes it possible to support
  more complex actor creation functionality, which could fail; e.g. loading
  credentials for a specific server from some source.
* The API for sending HTTP requests in `HttpRequestSender` has slightly
  changed: The parameters for the discard mode and the request data have
  changed their position (because the discard mode seems to be used more
  frequently). The request data now has the default value *null*.
* There is a new module _gdrive_ with a `FileSystem` implementation for the
  https://developers.google.com/drive/api/v3/reference[Google Drive API]. Thus,
  files and folders stored in Google Drive can now be manipulated.
* Fixed a bug in the OneDrive FileSystem implementation related to files with a
  size of 0. Such files could not be uploaded, causing file create or update
  operations to fail.
* `DavFileSystem` now handles multi-status responses received for _PROPPATCH_
  requests correctly; failures reported in such a response are now detected.

== Release 0.2 (2021-07-10)

* File systems now support HTTP proxies.
* A new module has been added that allows access to the local file system via
  the `FileSystem` API. This is, of course, somewhat a special case, as the
  implementation does not make use of HTTP requests. One use case of this
  module is to align the API when interacting with both servers and local
  files; it is, however, not intended for production-ready, high-performance
  file operations.
* Minor API improvements, e.g.:
** Some alignment has been done to create file system-specific file and folder
   objects.
** A new function has been added to the `FileSystem` interface allowing to
   modify the content and the attributes of a file with a single call.
* A few bug fixes for the protocols supported.

== Release 0.1 (2021-05-04)

The initial release.