= Release notes

This page contains information about the changes between the different versions
of the CloudFiles library.

== Release 0.3 (TBD)

* Fixed the encoding handling when resolving paths in LocalFileSystem. The
  `resolvePath()` function now correctly decodes the passed in strings before
  they are converted to `Path` objects.
* `ElementPatchSpec` no longer supports patching the description field. While
  concrete `FileSystem` implementations may need to modify certain attributes,
  it is very unlikely that this would be required for the description.
* The type of the `description` property of files and folders has been changed
  from `String` to `Option[String]`. This better reflects the usage in
  practice, and is also more in-line with many concrete `FileSystem`
  implementations, for which this attribute is optional or even not supported.
* Changed the `RequestActorFactory` function type in `MultiHostExtension`. The
  new type no longer returns an `ActorRef`, but a `Future` with a function that
  actually creates the new request actor. This makes it possible to support
  more complex actor creation functionality, which could fail; e.g. loading
  credentials for a specific server from some source.
* The API for sending HTTP requests in `HttpRequestSender` has slightly
  changed: The parameters for the discard mode and the request data have
  changed their position (because the discard mode seems to be used more
  frequently). The request data now has the default value *null*.

== Release 0.2 (2021-01-10)

* File systems now support HTTP proxies.
* A new module has been added that allows access to the local file system via
  the `FileSystem` API. This is, of course, somewhat a special case, as the
  implementation does not make use of HTTP requests. One use case of this
  module is to align the API when interacting with both servers and local
  files; it is, however, not intended for production-ready, high-performance
  file operations.
* Minor API improvements, e.g.:
** Some alignment has been done to create file system-specific file and folder
   objects.
** A new function has been added to the `FileSystem` interface allowing to
   modify the content and the attributes of a file with a single call.
* A few bug fixes for the protocols supported.

== Release 0.1 (2021-05-04)

The initial release.