:toc:
:toc-placement!:
:toclevels: 3
= CloudFiles Google Drive

This is the documentation of the CloudFiles _gdrive_ module which provides an implementation of the `FileSystem` abstraction for https://developers.google.com/drive/api/guides/about-sdk?hl=en[Google Drive].

toc::[]

== Synopsis
Google Drive provides a cloud storage for files. The files are owned by a specific user and can be shared with other users. In contrast to typical file system implementations, Google Drive is not strictly hierarchically organized. An item in the file system can have multiple parents, so there is not necessarily a single path under which an item can be represented.

Authentication to Google Drive is done via an OAuth access token. The token identifies the user and determines which files are visible and accessible. There is no such thing like a drive ID as in link:../onedrive/README.adoc[OneDrive], but the file system always represents a view from the perspective of the current user.

The Google Drive API uses JSON data structures to describe the items on the file system. In terms of the API, both files and folders are represented by a _File_ resource. Such a _File_ has the basic properties expected by the link:../core/README.adoc[core interfaces] of CloudFiles plus some additional properties specific to Google Drive. In addition, applications can store arbitrary custom properties (as string-based key-value pairs) together with a file. This module defines corresponding model classes to handle these structures.

The `FileSystem` implementation for Google Drive implements the `ExtensibleFileSystem` trait and can thus be used together with all extension file systems available.

== Usage
This section contains usage instructions for the Google Drive file system implementation. The main implementation class is link:src/main/scala/com/github/cloudfiles/gdrive/GoogleDriveFileSystem.scala[GoogleDriveFileSystem].

=== Creating a file system
The _gdrive_ module defines the link:src/main/scala/com/github/cloudfiles/gdrive/GoogleDriveConfig.scala[GoogleDriveConfig] class that contains the properties supported by the Google Drive-specific file system implementation. To create a file system object, such a configuration has to be created and passed to the constructor of `GoogleDriveFileSystem`. In fact, the class defines default values for all properties that are suitable for many use cases, which further simplifies the creation of a file system. Table <<tab_google_drive_config>> lists the available configuration options.

[#tab_google_drive_config]
.Configuration properties for Google Drive
[cols="1,3,1",options="header"]
|===
|Property |Description |Default

|optRootPath
|An `Option` defining the root path to be used by the file system. This path is automatically prepended to other paths. As stated above, the Google Drive file system is not strictly hierarchical. So, setting a root path does not necessarily restrict access to a specific sub structure, since files could be reached via alternative paths.
|None

|timeout
|A timeout for network operations. Operations that take longer are canceled and considered as failures.
|30 seconds

|includeTrashed
|Google Drive has a special notion of files moved to the trash. They remain existing at their current position in the file system, but are marked as trashed. Setting this property to *true* makes such files visible; they are then returned in the content of their parent folders.
|false

|serverUri
|An alternative URL for the Google Drive API. This is probably rarely needed in practice. The CloudFiles library itself makes use of this for testing purposes; but if somebody decides to host a Google Drive server on premise, this URL can be specified.
|Google API
|===

The Google Drive API uses OAuth for authentication (see https://developers.google.com/identity/protocols/oauth2?hl=en[Using OAuth 2.0 to Access Google APIs]). This means that the link:../core/README.adoc#_httprequestsender[HttpRequestSender] actor used for executing file system operations must be decorated by the link:../core/README.adoc#auth_oauth[OAuthExtension]. Other than that, the file system implementation does not put any restrictions on the HTTP sender actor.

=== Item model
The data types for files and folders used by `GoogleDriveFileSystem` are defined in the link:src/main/scala/com/github/cloudfiles/gdrive/GoogleDriveModel.scala[GoogleDriveModel] module. They are named `GoogleDriveFile` and `GoogleDriveFolder` and are derived from a common base trait `GoogleDriveElement`. This trait wraps a `File` resource from the Google Drive API and provides the standard properties for files and folders by delegating to this object. To represent the metadata available for files in Google Drive, the link:src/main/scala/com/github/cloudfiles/gdrive/GoogleDriveJsonProtocol.scala[GoogleDriveJsonProtocol] module defines a number of data classes.

The model classes extend the base traits from the _core_ module, so access to basic properties and interoperability with other file system implementations is possible.

For creating new file or folder instances - which is needed for invoking a number of operations that expect such objects as parameters -, clients can use the convenience functions `newFile()` or `newFolder()` respectively from `GoogleDriveModel`. These functions are easy to use, since clients only have to pass relevant properties; all other properties are set to default values.

The non-hierarchical nature of Google Drive has an impact on the functions to resolve files and folders based on their paths. They are quite expensive, since they may have to search multiple paths in the graph of folders. Therefore, the recommendation is to access items on the file system using their IDs as far as possible.