:toc:
:toc-placement!:
:toclevels: 3
= CloudFiles Crypt

This is the documentation of the CloudFiles _crypt_ module which provides multiple implementations of the `FileSystem` abstraction that are related to encryption of data.

toc::[]

== Synopsis
This module provides `FileSystem` implementations that can decorate other file systems (implementing the link:../core/README.adoc#extensible_file_systems[ExtensibleFileSystem] trait) to support different kinds of encryption. This encryption happens transparently to the underlying file systems: when data is stored on a target file system it is encrypted; when it is accessed later it is decrypted on the fly again. This means that a client of these file systems sees plain data, while the data on the target file system is actually encrypted. This functionality is especially useful when storing sensitive information on public servers or in the cloud.

The _crypt_ module supports the following `FileSystem` implementations:

.Encrypting file system implementations
[cols="1,3",options="header"]
|===
|File system |Description

|CryptContentFileSystem
|A file system that encrypts the content of files stored on the underlying file system.

|CryptNamesFileSystem
|A file system that encrypts the names of files and folders, but does not manipulate the content of files.
|===

These file systems can be used in isolation or in combination with each other. For some use cases, it might not be sufficient to encrypt only the content of files if from their names information about them could already leak.

The _crypt_ module defines an abstraction for algorithms to encrypt and decrypt data. This makes it possible to plug in different encryption schemes.

== Algorithm abstraction
The `FileSystem` implementations from this module do not implement encryption or decryption logic by themselves, but delegate to special algorithm objects for this purpose. There are two traits for such algorithm implementations as listed by table <<tab_algorithm_interface>>.

[#tab_algorithm_interface]
.Traits for crypt algorithms
[cols="1,3",options="header"]
|===
|Trait |Description

|CryptCipher
|Analogously to a `javax.crypto.Cipher` object, this trait defines the functions to execute a cryptographic operation, i.e. an encryption or decryption of data. The protocol consists of initializing the object, passing data to it, and notifying it that all data has been passed. Each step returns transformed data which (when aggregated) is the result of the operation.

|CryptAlgorithm
|This trait represents a specific cryptographic algorithm. It allows obtaining specialized `CryptCipher` objects for encrypt and decrypt operations. In addition, there are functions for calculating the encrypted and decrypted size of data. This is needed, since for uploading or downloading data via a file system the size of the stream must be known beforehand.
|===

The traits can be found in the link:src/main/scala/com/github/cloudfiles/crypt/alg/[alg] package. Refer to the ScalaDocs for further information.

== Usage
This section contains instructions how to use the file system implementations provided by the _crypt_ module.

=== CryptContentFileSystem
The link:src/main/scala/com/github/cloudfiles/crypt/fs/CryptContentFileSystem.scala[CryptContentFileSystem] class adds the functionality to another file system to encrypt files when they are uploaded and to decrypt them when they are downloaded again. So, persistent data is encrypted, but users accessing it see the plain content of files.

Usage of this class is rather straight-forward: When creating an instance, pass in the file system to be decorated and an object with configuration settings. Then the instance can be used like any other file system, and it exposes the data of the decorated file system; the encrypt and decrypt operations happen transparently behind the scenes.

The object with the configuration is of type link:src/main/scala/com/github/cloudfiles/crypt/fs/CryptConfig.scala[CryptConfig]. It provides the settings as described in table <<tab_crypt_config>>.

[#tab_crypt_config]
.Configuration of an encrypted file system
[cols="1,3",options="header"]
|===
|Property |Description

|algorithm
|The algorithm to use for encrypting and decrypting data in form of an object implementing the `CryptAlgorithm` trait.

|keyEncrypt
|The `java.security.Key` to use for encrypting data. The concrete class of this key must be compatible with what the algorithm expects.

|keyDecrypt
|The `java.security.Key` to use for decrypting data. This is analogous to `keyEncrypt`, but for decryption. For symmetric algorithms, the same key can be used for encryption and decryption; otherwise, there will be different keys.

|secRandom
|An instance of `java.security.SecureRandom` used as a source for randomness. Such an object is needed by the algorithm to initiate encrypt and decrypt operations.
|===

Note that `CryptContentFileSystem` can be used together with arbitrary `ExtensibleFileSystem` implementations, but it places some restrictions on the type parameters: Since some attributes of files have to be adjusted dynamically, they must be represented by the base trait defined in the link:../core/README.adoc[core] module. The same is true for the type used for the content of folders.

There is one caveat when using `CryptContentFileSystem` to decorate another file system: The implementation assumes that all files on the underlying file system have been encrypted using the configured algorithm. Files stored in plain text will nevertheless be decrypted resulting in garbage. So, in case of mixed content, it is in the responsibility of the client to keep a reference to the decorated file system and use this one to access unencrypted files.
